# Write a Makefile that will, by default, build the crawler executable program.
# Add a make clean target that removes files produced by Make or your tests.
# Add a make test target that tests your crawler. Read about testing below.
# Save the output of your tests with make test &> testing.out.
